### ISSUE TITLE
[ChunkyMap 1.x] extrazoomout option in worlds.txt causes black render

### ISSUE THREAD

**Issue by mruk** [leMaik/ChunkyMap#25]
It was surprising issue from logical point of view, and took me some hours to find which worlds settings is the problematic -

> java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
...
[INFO]: [ChunkyMap] Loading ChunkyMap v1.2.0
[INFO]: [dynmap] Loading dynmap v2.6-beta-1-Dev201807082003
[INFO]: [dynmap] version=git-Bukkit-e60fc34 (MC: 1.12.2)
...  

worlds.txt
```
worlds:
  - name: world
    extrazoomout: 2
    maps:
#      - class: org.dynmap.hdmap.HDMap
      - class: de.lemaik.chunkymap.dynmap.ChunkyMap
```
OBSERVATION: extrazoomout > 2 causes rendering black tiles with class: de.lemaik.chunkymap.dynmap.ChunkyMap.
Standard (class: org.dynmap.hdmap.HDMap) works correctly.
