### ISSUE TITLE
Radiusrender uses the default dynmap's renderer instead of Chunky

### ISSUE THREAD

**Issue by owlnull** [leMaik/ChunkyMap#34]
## Expected behavior

Radiusrender uses Chunky 

## Actual behavior

Basically, if I run the radiusrender (for example, `/dynmap radiusrender 32`), the tiles are rendered like using the default dynmap's renderer without shadows

![screenshot](https://user-images.githubusercontent.com/60847190/121672791-a4612800-cac9-11eb-9392-a7e5a78169ed.png)

At the same time, fullrender works as expected and uses Chunky

## Map config

```yaml
- class: de.lemaik.chunkymap.dynmap.ChunkyMap
  name: surfacert
  prefix: chunky
  title: Surface RT
  perspective: iso_SE_30_hires
  mapzoomin: 1
  chunkyThreads: 4
  samplesPerPixel: 32
  templateScene: chunkyScene.json
  denoiser:
    enabled: false
  chunkPadding: 2
```

## ChunkyMap versions tested

- v2.6.0-pre2
- v2.5.2

### Dynmap 

```
core=3.1-457, plugin=3.1-457
```

### Paper server

```
git-Paper-775 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
```

### Java

```
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing
```

### Linux

```
5.12.5-arch1-1
```
