### ISSUE TITLE
[BUG] 2.6.0-pre4 - resourcepacks error

### ISSUE THREAD

**Issue by denny4-user** [leMaik/ChunkyMap#58]
in this version in `world.txt` - the function for loading custom textures does not work properly.

`"resourcepacks"` - **doesn't work**, `"texturepack"` **works** -> which contradicts the guide in the README

Example of a WORKING config:

*upload textures (.zip) along the path `plugins/dynmap`
*insert this config into `plugins/dynmap/worlds.txt`

```
worlds:
  - name: world
    maps:
      - class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: chunky
        title: World
        perspective: iso_SE_30_hires
        texturepack: resourcepack.zip
```
