### ISSUE TITLE
Using `2.6.0-pre4` (have not tested other versions) on 1.19.2 (`git-Purpur-1858 (MC: 1.19.2)`), I get only blank images. Have I misconfigured something?

### ISSUE THREAD

**Issue by leMaik** [leMaik/ChunkyMap#59]
Using `2.6.0-pre4` (have not tested other versions) on 1.19.2 (`git-Purpur-1858 (MC: 1.19.2)`), I get only blank images. Have I misconfigured something?

from `worlds.txt`
```yaml
worlds:
-   name: world
    title: Overworld
    enabled: true
    extrazoomout: 2
    maps:
    -   class: de.lemaik.chunkymap.dynmap.ChunkyMap
        chunkyThreads: 4
        name: surface
        title: Surface
        perspective: iso_SE_30_hires
        prefix: t
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
        mapzoomout: 3
        boostzoom: 2
```

from `configuration.txt`
```yaml
defaulttilescale: 2

storage:
  type: filetree

image-format: jpg-q90
```

The images are black, and seem to get deleted (possibly since they are blank?) soon after generation.

Java Version:

```
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment (build 19+36-2238)
OpenJDK 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
```

_Originally posted by @TMUniversal in https://github.com/leMaik/ChunkyMap/issues/46#issuecomment-1483822774_
