### ISSUE TITLE
2.7.0-pre1 cannot render

### ISSUE THREAD

**Issue by ChunghwaMC** [leMaik/ChunkyMap#62]
log
```
[19:11:52 WARN]: [ChunkyMap] Rendering tile 389460_-102417 failed
java.lang.NullPointerException: Cannot invoke "java.nio.file.FileSystem.close()" because "this.fileSystem" is null
        at ChunkyMap-2.7.0-pre1.jar/se.llbit.chunky.resources.LayeredResourcePacks$ResourcePack.close(LayeredResourcePacks.java:113) ~[ChunkyMap-2.7.0-pre1.jar:?]
        at ChunkyMap-2.7.0-pre1.jar/se.llbit.chunky.resources.LayeredResourcePacks.close(LayeredResourcePacks.java:68) ~[ChunkyMap-2.7.0-pre1.jar:?]
        at ChunkyMap-2.7.0-pre1.jar/se.llbit.chunky.resources.ResourcePackLoader.loadResourcePacks(ResourcePackLoader.java:135) ~[ChunkyMap-2.7.0-pre1.jar:?]
        at ChunkyMap-2.7.0-pre1.jar/de.lemaik.chunkymap.rendering.local.ChunkyRenderer.render(ChunkyRenderer.java:80) ~[ChunkyMap-2.7.0-pre1.jar:?]
        at ChunkyMap-2.7.0-pre1.jar/de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:69) ~[ChunkyMap-2.7.0-pre1.jar:?]
        at Dynmap-3.7-beta-8-spigot.jar/org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:812) ~[Dynmap-3.7-beta-8-spigot.jar:?]
        at Dynmap-3.7-beta-8-spigot.jar/org.dynmap.MapManager$FullWorldRenderState.access$1300(MapManager.java:271) ~[Dynmap-3.7-beta-8-spigot.jar:?]
        at Dynmap-3.7-beta-8-spigot.jar/org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:693) ~[Dynmap-3.7-beta-8-spigot.jar:?]
        at Dynmap-3.7-beta-8-spigot.jar/org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:691) ~[Dynmap-3.7-beta-8-spigot.jar:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
world.txt
```
worlds:
  - name: YouliYuersworld
    bigworld: true
    extrazoomout: 13
    maps:
      - class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: flat
        prefix: flat
        perspective: iso_S_90_64x
        shader: stdtexture
        lighting: shadows-smooth
        mapzoomin: 0
        chunkyThreads: 2
        samplesPerPixel: 100
        texturepack: chunghwamc.zip
        texturepackVersion: 1.20.4
        chunkPadding: 7
```
custom-perspectives.txt
```
perspectives:
  - class: org.dynmap.hdmap.IsoHDPerspective 
    name: iso_S_90_64x
    azimuth: 180
    inclination: 90
    scale: 64
```
