### ISSUE TITLE
Rendering issue in version 2.7.0-pre1

### ISSUE THREAD

**Issue by AF91Nx** [leMaik/ChunkyMap#63]
This is a new map used for testing version chunkymap 2.7.0-pre1 (1.21.4).

log
```
[07:05:03] [Dynmap Render Thread/WARN]: [ChunkyMap] Rendering tile 0_16 failed
java.util.concurrent.ExecutionException: de.lemaik.chunkymap.rendering.RenderException: Rendering failed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at ChunkyMap-2.7.0-pre1.jar/de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:166) ~[ChunkyMap-2.7.0-pre1.jar:?]
	at Dynmap-3.7-beta-8-spigot.jar/org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:812) ~[Dynmap-3.7-beta-8-spigot.jar:?]
	at Dynmap-3.7-beta-8-spigot.jar/org.dynmap.MapManager$FullWorldRenderState.access$1300(MapManager.java:271) ~[Dynmap-3.7-beta-8-spigot.jar:?]
	at Dynmap-3.7-beta-8-spigot.jar/org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:693) ~[Dynmap-3.7-beta-8-spigot.jar:?]
	at Dynmap-3.7-beta-8-spigot.jar/org.dynmap.MapManager$FullWorldRenderState$3.call(MapManager.java:691) ~[Dynmap-3.7-beta-8-spigot.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: de.lemaik.chunkymap.rendering.RenderException: Rendering failed
	at ChunkyMap-2.7.0-pre1.jar/de.lemaik.chunkymap.rendering.local.ChunkyRenderer.render(ChunkyRenderer.java:123) ~[ChunkyMap-2.7.0-pre1.jar:?]
	at ChunkyMap-2.7.0-pre1.jar/de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:69) ~[ChunkyMap-2.7.0-pre1.jar:?]
	... 9 more
Caused by: java.lang.InterruptedException
	at java.base/java.lang.Object.wait0(Native Method) ~[?:?]
	at java.base/java.lang.Object.wait(Object.java:366) ~[?:?]
	at java.base/java.lang.Thread.join(Thread.java:2079) ~[?:?]
	at java.base/java.lang.Thread.join(Thread.java:2155) ~[?:?]
	at ChunkyMap-2.7.0-pre1.jar/de.lemaik.chunkymap.rendering.local.ChunkyRenderer.render(ChunkyRenderer.java:120) ~[ChunkyMap-2.7.0-pre1.jar:?]
	at ChunkyMap-2.7.0-pre1.jar/de.lemaik.chunkymap.dynmap.ChunkyMapTile.render(ChunkyMapTile.java:69) ~[ChunkyMap-2.7.0-pre1.jar:?]
	... 9 more

```
world.txt
```
-   name: RT_TEST
    title: RT_TEST
    enabled: true
    extrazoomout: 2
    maps:
    -   class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: surface20SE_RT
        title: surface20SE_RT
        icon: images/block_surface20SE_RT.png
        prefix: surface20SE_RT
        perspective: iso_SE_20_hires
        shader: stdtexture
        lighting: default
        image-format: default
        requeueFailedTiles: true
        chunkPadding: 2
        mapzoomin: 1
        mapzoomout: 5
        boostzoom: 0
        readonly: true
    -   class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: surface20SE_night_RT
        title: surface20SE_night_RT
        icon: images/block_surface20SE_night_RT.png
        prefix: surface20SE_night_RT
        perspective: iso_SE_20_hires
        shader: stdtexture
        templateScene: nightscene.json
        lighting: default
        image-format: default
        requeueFailedTiles: true
        chunkPadding: 1
        mapzoomin: 1
        mapzoomout: 5
        boostzoom: 0
        readonly: true
    -   class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: surface20NW_RT
        title: surface20NW_RT
        icon: images/block_surface20NW_RT.png
        prefix: surface20NW_RT
        perspective: iso_NW_20_hires
        shader: stdtexture
        lighting: default
        image-format: default
        requeueFailedTiles: true
        chunkPadding: 2
        mapzoomin: 1
        mapzoomout: 5
        boostzoom: 0
        readonly: true
    -   class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: surface20NW_night_RT
        title: surface20NW_night_RT
        icon: images/block_surface20NW_night_RT.png
        prefix: surface20NW_night_RT
        perspective: iso_NW_20_hires
        shader: stdtexture
        templateScene: nightscene.json
        lighting: default
        image-format: default
        requeueFailedTiles: true
        chunkPadding: 1
        mapzoomin: 1
        mapzoomout: 5
        boostzoom: 0
        readonly: true
```

Rendered output looks like this:
![Image](https://images.plurk.com/2cDWXirz9IENQ2zs7k4dNO.png)

`templateScene`  appears to be broken.
This issue did not occur in earlier versions.

nightscene.json
```
{
  "emittersEnabled": true,
  "emitterIntensity":15,
  "sunEnabled":false,
  "fastFog": false,
  "transparentSky":false,
  "emitterSamplingStrategy": "ONE",
  "fogDensity":0.0,
}
```
![Image](https://images.plurk.com/4wyauQHaNArwsbd7jOVL9R.png)
Some sections appear as if they're only partially rendered, as if the rendering process stops midway.

Equipment: 7950X CPU + 64GB ECC RAM.

dynmap:
[http://af.furry.tw:9123/?worldname=RT_TEST&mapname=surface20SE_RT&zoom=5&x=-14&y=64&z=2](url)
