### ISSUE TITLE
Weird interaction with multiple maps for a world

### ISSUE THREAD

**Issue by stormboomer** [leMaik/ChunkyMap#7]
I've found a weird interaction when using 2 Maps for one world. 
When doing a (radius)render the world first renders the chunky map, using chunky. After the Chunky Map render is done, the "Surface Day" render is started, it then overwrites the rendered Chunky scene with the default dynmap rendering output.
I think that I might missed out a config param, this is my worlds.txt
```YML
worlds:
  - name: world
    maps:
      - class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: chunky
        title: World
        prefix: chunky
        perspective: iso_SE_30_hires
        shader: customshader
        samplesPerPixel: 10
        chunkyThreads: 8
        chunkPadding: 2
        texturepack: texturepacks/texturepack.zip
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: Surface Day
        icon: images/block_surface.png
        prefix: surface
        perspective: iso_SE_30_hires
        shader: customshader
        lighting: shadows
```
Server: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Dynmap: Dynmap v3.0-beta-5-218
ChunkyMap: ChunkyMap-2.0.0 (you might need to update plugin.yml, it still gives 1.2.0 when launched)
