### ISSUE TITLE
Number of render threads

### ISSUE THREAD

**Issue by Retidurc** [leMaik/ChunkyMap#9]
I have this set in world.txt 
```yml      
worlds:
  - name: monarudo
    maps:
      - class: de.lemaik.chunkymap.dynmap.ChunkyMap
        name: chunky
        title: "Surface"
        perspective: iso_SE_30_hires
        chunkyThreads: 4
```

but chunkyMap seems to create a huge amount of threads to render :
![image](https://user-images.githubusercontent.com/6501482/77862157-fb0e7900-7219-11ea-9d55-edf7c92f6da2.png)

Maybe this is just a misunderstanding of the "chunkyThreads: 4" configuration option, not sure .

I was trying to limit the impact of chunkyMap on TPS loss, maybe there is another setting to do that ? I tried several things on dynmap side but no success so far
